export {default as Header} from './header/Header'
export {default as Main} from './main/Main'
export {default as Footer} from './footer/Footer'
export {default as Logo} from './logo/Logo'
export {default as RecentBlogPost} from './recent-blog-post/RecentBlogPost'
export {default as PostDesign} from './post-design/PostDesign'